### ISSUE TITLE
grunt initial fails

### ISSUE THREAD

**Issue by umeboshi2** [6502ts/6502.ts#67]
"src/machine/stella/cartridge/CartridgeFE.ts(110,13): error TS6133: '_cpu' is declared but its value is never read."

It looks like you are preparing for release, so there might be a unexpected change, or the repo isn't ready now.  I looked at repo and it looks like you are refactoring.

I followed the instructions and grunt fails on "ts:main" task:

```console
(main) umeboshi@bard:~/workspace/others/6502.ts$ grunt initial
Running "notify_hooks" task

Running "clean:base" (clean) task
>> 2 paths cleaned.

Running "clean:mrproper" (clean) task
>> 1 path cleaned.

Running "copy:install" (copy) task
Copied 4 files

Running "exec:tslint" (exec) task

Running "ts:main" (ts) task
Compiling...
Using tsc v2.6.2
src/machine/stella/cartridge/CartridgeFE.ts(110,13): error TS6133: '_cpu' is declared but its value is never read.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:main" failed. Use --force to continue.

Aborted due to warnings.
```

I am using node v6:

```console
(main) umeboshi@bard:~/workspace/others/6502.ts$ node -v
v6.12.1
(main) umeboshi@bard:~/workspace/others/6502.ts$ npm version
{ '6502.ts': '0.0.0',
  npm: '5.6.0',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '58.2',
  modules: '48',
  node: '6.12.1',
  openssl: '1.0.2m',
  uv: '1.15.0',
  v8: '5.1.281.109',
  zlib: '1.2.11' }
```

Since you are refactoring, I decided to test the github.io branch:

```console
(main) umeboshi@bard:~/workspace/others/6502.ts$ git checkout github.io 
Branch github.io set up to track remote branch github.io from origin.
Switched to a new branch 'github.io'
(main) umeboshi@bard:~/workspace/others/6502.ts$ npm install             
npm WARN 6502.ts@0.0.0 No repository field.
npm WARN 6502.ts@0.0.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

removed 50 packages in 22.449s
(main) umeboshi@bard:~/workspace/others/6502.ts$ grunt initial
Running "notify_hooks" task

Running "clean:base" (clean) task
>> 0 paths cleaned.

Running "clean:mrproper" (clean) task
>> 0 paths cleaned.

Running "copy:install" (copy) task
Copied 4 files

Running "exec:tslint" (exec) task

Running "ts:main" (ts) task
Compiling...
Using tsc v2.6.2
src/machine/stella/cartridge/CartridgeFE.ts(110,13): error TS6133: '_cpu' is declared but its value is never read.

>> 1 non-emit-preventing type warning  
>> Error: tsc return code: 2
Warning: Task "ts:main" failed. Use --force to continue.

Aborted due to warnings.
```

**Comment by DirtyHairy** [comment]
Hi @umeboshi2!

Thanks for the pointer. I switched to Yarn for package management some time ago and am depending on its lockfile to pull in the correct dependencies. I forgot to update the readme accordingly, my bad. Can you retry with yarn? This should do the trick.

The issue you stumbled across is a minor regression with TS 2.6 --- I've got that on my agenda, together with a full dependency upgrade. The repository compiles and works fine, so if you'd like to poke around, go ahead :) I am preparing to release an embeddable version of the VCS emulator (both on NPM and as a browser bundle) soon, that's the reason for the refactoring commits.

**Comment by DirtyHairy** [comment]
As a sidenote: I just updated all dependencies, including TS to their latest versions and fixed the build with ts 2.6.

**Comment by umeboshi2** [comment]
Thanks!  I started using yarn last summer, but went back to npm when it got better.  Yarn has some severe deficiencies that hamper me at times. (91d4e64ef7e4ec4f53d0e3533b5cc849958104a0).

I will install it again (and add the darned mutex config).  I happened to notice the yarn.lock, but I thought it was just used for CI or similar.  Thanks!

**Comment by umeboshi2** [comment]
@DirtyHairy thanks for helping maintain stella!  I got here earlier when playing with emscripten and using stella from debian.  I didn't know that it was being maintained here.  Cute port #'s for grunt serve.  I was still using github.io branch and noticed that you updated dependencies.  It worked on github.io branch using yarn.

It's working in master using yarn.
Is coffeescript being used?

**Comment by umeboshi2** [comment]
@DirtyHairy, It seems that after you updated the dependencies, ```npm install``` works correctly.

**Comment by DirtyHairy** [comment]
Thanks a lot for the thumbs up :smirk: Actually, everything Stella is maintained in the Stella repository over [there](https://github.com/stella-emu/stella) with @sa666666 being the main developer. 6502.ts is much younger than Stella, and the link between the two projects originates with the TIA core that I ported from 6502.ts to Stella last year. Since then, more aspects of  both projects' emulation cores have evolved together, so there are more connections by now, but only in concept --- there is no actual code being shared.

As for 6502.ts, there is no Coffeescript involved, the code is 100% [Typescript](https://www.typescriptlang.org) + a [JS port](https://github.com/DirtyHairy/thumbulator.ts) of the [Thumbulator](https://github.com/dwelch67/thumbulator) that I did with emscripten (for ARM emulation).

Concerning yarn, I have never had any issues with it locally, but I remember there were major issues (presumably related to file system locking) with it on travis before @mschroeder fixed the Travis config. 😏

**Comment by umeboshi2** [comment]
I have been spending the xmas season learning and playing with emscripten, which is how I got here.  I noticed coffeescript give a warning during the install.  It seems that it's needed by grunt and not used.

**Comment by DirtyHairy** [comment]
I see. Yeah, I guess it used somewhere in the dependency chain.
